// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FinnTR.proto

package de.tubs.cs.ibr.finn.station;

public final class FinnTrProtocol {
  private FinnTrProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class command extends
      com.google.protobuf.GeneratedMessage {
    // Use command.newBuilder() to construct.
    private command() {
      initFields();
    }
    private command(boolean noInit) {}
    
    private static final command defaultInstance;
    public static command getDefaultInstance() {
      return defaultInstance;
    }
    
    public command getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.tubs.cs.ibr.finn.station.FinnTrProtocol.internal_static_controller_command_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.tubs.cs.ibr.finn.station.FinnTrProtocol.internal_static_controller_command_fieldAccessorTable;
    }
    
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional int32 destination = 2;
    public static final int DESTINATION_FIELD_NUMBER = 2;
    private boolean hasDestination;
    private int destination_ = 0;
    public boolean hasDestination() { return hasDestination; }
    public int getDestination() { return destination_; }
    
    // optional bytes bytes = 3;
    public static final int BYTES_FIELD_NUMBER = 3;
    private boolean hasBytes;
    private com.google.protobuf.ByteString bytes_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasBytes() { return hasBytes; }
    public com.google.protobuf.ByteString getBytes() { return bytes_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      if (hasDestination()) {
        output.writeInt32(2, getDestination());
      }
      if (hasBytes()) {
        output.writeBytes(3, getBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      if (hasDestination()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getDestination());
      }
      if (hasBytes()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static de.tubs.cs.ibr.finn.station.FinnTrProtocol.command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.tubs.cs.ibr.finn.station.FinnTrProtocol.command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.tubs.cs.ibr.finn.station.FinnTrProtocol.command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.tubs.cs.ibr.finn.station.FinnTrProtocol.command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.tubs.cs.ibr.finn.station.FinnTrProtocol.command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.tubs.cs.ibr.finn.station.FinnTrProtocol.command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.tubs.cs.ibr.finn.station.FinnTrProtocol.command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.tubs.cs.ibr.finn.station.FinnTrProtocol.command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.tubs.cs.ibr.finn.station.FinnTrProtocol.command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.tubs.cs.ibr.finn.station.FinnTrProtocol.command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.tubs.cs.ibr.finn.station.FinnTrProtocol.command prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private de.tubs.cs.ibr.finn.station.FinnTrProtocol.command result;
      
      // Construct using de.tubs.cs.ibr.finn.station.FinnTrProtocol.command.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new de.tubs.cs.ibr.finn.station.FinnTrProtocol.command();
        return builder;
      }
      
      protected de.tubs.cs.ibr.finn.station.FinnTrProtocol.command internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new de.tubs.cs.ibr.finn.station.FinnTrProtocol.command();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.tubs.cs.ibr.finn.station.FinnTrProtocol.command.getDescriptor();
      }
      
      public de.tubs.cs.ibr.finn.station.FinnTrProtocol.command getDefaultInstanceForType() {
        return de.tubs.cs.ibr.finn.station.FinnTrProtocol.command.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public de.tubs.cs.ibr.finn.station.FinnTrProtocol.command build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private de.tubs.cs.ibr.finn.station.FinnTrProtocol.command buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public de.tubs.cs.ibr.finn.station.FinnTrProtocol.command buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        de.tubs.cs.ibr.finn.station.FinnTrProtocol.command returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.tubs.cs.ibr.finn.station.FinnTrProtocol.command) {
          return mergeFrom((de.tubs.cs.ibr.finn.station.FinnTrProtocol.command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.tubs.cs.ibr.finn.station.FinnTrProtocol.command other) {
        if (other == de.tubs.cs.ibr.finn.station.FinnTrProtocol.command.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasDestination()) {
          setDestination(other.getDestination());
        }
        if (other.hasBytes()) {
          setBytes(other.getBytes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 16: {
              setDestination(input.readInt32());
              break;
            }
            case 26: {
              setBytes(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // optional int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional int32 destination = 2;
      public boolean hasDestination() {
        return result.hasDestination();
      }
      public int getDestination() {
        return result.getDestination();
      }
      public Builder setDestination(int value) {
        result.hasDestination = true;
        result.destination_ = value;
        return this;
      }
      public Builder clearDestination() {
        result.hasDestination = false;
        result.destination_ = 0;
        return this;
      }
      
      // optional bytes bytes = 3;
      public boolean hasBytes() {
        return result.hasBytes();
      }
      public com.google.protobuf.ByteString getBytes() {
        return result.getBytes();
      }
      public Builder setBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasBytes = true;
        result.bytes_ = value;
        return this;
      }
      public Builder clearBytes() {
        result.hasBytes = false;
        result.bytes_ = getDefaultInstance().getBytes();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:controller.command)
    }
    
    static {
      defaultInstance = new command(true);
      de.tubs.cs.ibr.finn.station.FinnTrProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:controller.command)
  }
  
  public static final class Envelope extends
      com.google.protobuf.GeneratedMessage {
    // Use Envelope.newBuilder() to construct.
    private Envelope() {
      initFields();
    }
    private Envelope(boolean noInit) {}
    
    private static final Envelope defaultInstance;
    public static Envelope getDefaultInstance() {
      return defaultInstance;
    }
    
    public Envelope getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.tubs.cs.ibr.finn.station.FinnTrProtocol.internal_static_controller_Envelope_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.tubs.cs.ibr.finn.station.FinnTrProtocol.internal_static_controller_Envelope_fieldAccessorTable;
    }
    
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional int32 command = 2;
    public static final int COMMAND_FIELD_NUMBER = 2;
    private boolean hasCommand;
    private int command_ = 0;
    public boolean hasCommand() { return hasCommand; }
    public int getCommand() { return command_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      if (hasCommand()) {
        output.writeInt32(2, getCommand());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      if (hasCommand()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getCommand());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope result;
      
      // Construct using de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope();
        return builder;
      }
      
      protected de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope.getDescriptor();
      }
      
      public de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope getDefaultInstanceForType() {
        return de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope) {
          return mergeFrom((de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope other) {
        if (other == de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 16: {
              setCommand(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional int32 command = 2;
      public boolean hasCommand() {
        return result.hasCommand();
      }
      public int getCommand() {
        return result.getCommand();
      }
      public Builder setCommand(int value) {
        result.hasCommand = true;
        result.command_ = value;
        return this;
      }
      public Builder clearCommand() {
        result.hasCommand = false;
        result.command_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:controller.Envelope)
    }
    
    static {
      defaultInstance = new Envelope(true);
      de.tubs.cs.ibr.finn.station.FinnTrProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:controller.Envelope)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_controller_command_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_controller_command_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_controller_Envelope_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_controller_Envelope_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014FinnTR.proto\022\ncontroller\"9\n\007command\022\n\n" +
      "\002id\030\001 \001(\005\022\023\n\013destination\030\002 \001(\005\022\r\n\005bytes\030" +
      "\003 \001(\014\"\'\n\010Envelope\022\n\n\002id\030\001 \001(\005\022\017\n\007command" +
      "\030\002 \001(\005B-\n\033de.tubs.cs.ibr.finn.stationB\016F" +
      "innTrProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_controller_command_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_controller_command_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_controller_command_descriptor,
              new java.lang.String[] { "Id", "Destination", "Bytes", },
              de.tubs.cs.ibr.finn.station.FinnTrProtocol.command.class,
              de.tubs.cs.ibr.finn.station.FinnTrProtocol.command.Builder.class);
          internal_static_controller_Envelope_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_controller_Envelope_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_controller_Envelope_descriptor,
              new java.lang.String[] { "Id", "Command", },
              de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope.class,
              de.tubs.cs.ibr.finn.station.FinnTrProtocol.Envelope.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
